version: "3"

services:
  docker_devnet:
    image: trufflesuite/ganache-cli:v6.1.8
    command: |
      --verbose
      --networkId 7777777
      --gasLimit 0xfffffffffff
      --port 9545
      --deterministic
      --account="${npm_package_config_unlockedAccount0},${npm_package_config_etherBalance}"
      --account="${npm_package_config_unlockedAccount1},${npm_package_config_etherBalance}"
      --account="${npm_package_config_unlockedAccount2},${npm_package_config_etherBalance}"
    ports:
      - "9545:9545"

  wallet:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null
    working_dir: /wallet
    environment:
      - GANACHE_URL=http://docker_devnet:9545
      - npm_package_config_unlockedAccount0
      - npm_package_config_unlockedAccount1
      - npm_package_config_unlockedAccount2
      - npm_package_config_etherBalance
    volumes:
      - .:/wallet
    depends_on:
      - docker_devnet

  serve_files:
    image: halverneus/static-file-server:latest
    environment:
      - PORT=8000
      - FOLDER=/web
    volumes:
      - .:/web
    ports:
      - "8000:8000"
